spring:
  application:
    name: identity-svc
  # Para que tome Config Server desde env
  config:
    import: optional:configserver:${SPRING_CONFIG_IMPORT:}

management:
  endpoints.web.exposure.include: health,info
  endpoint:
    health:
      show-details: when-authorized
